require("plugins.plugins-setup")
require("core.options")
require("core.keymaps")
-- 插件
require("plugins/lualine")
require("plugins/alpha-nvim")
require("plugins/nvim-tree")
require("plugins/treesitter")
require("plugins/lsp")
require("plugins/cmp")
require("plugins/comment")
require("plugins/autopairs")
require("plugins/bufferline")
require("plugins/gitsigns")
require("plugins/telescope")
require("plugins/toggleterm")
require("plugins/hop")
